exports.fortunes = [
"A day for firm decisions!",
"A few hours grace before the madness begins again.",
"A gift of a flower will soon be made to you.",
"A long-forgotten loved one will appear soon.",
"A visit to a fresh place will bring strange work.",
"A visit to a strange place will bring fresh work.",
"A vivid and creative mind characterizes you.",
"Abandon the search for Truth; settle for a good fantasy.",
"Accent on helpful side of your nature.  Drain the moat.",
"Advancement in position.",
"After your lover has gone you will still have your SELF!",
"Afternoon very favorable for romance.",
"All the troubles you have will pass away very quickly.",
"Among the lucky, you are the chosen one.",
"An avocado-tone refrigerator would look good on your resume.",
"An exotic journey in a majestic far off land is in your future.",
"Another good night not to sleep in a eucalyptus tree.",
"Are you making all this up as you go along?",
"Artistic ventures highlighted.  Rob a museum.",
"Avert misunderstanding by calm, poise, and balance.",
"You will soon witness a miracle.",
"Avoid reality at all costs.",
"Bank error in your favor.  Collect $200.",
"Be cautious in your daily affairs.",
"Be cheerful while you are alive.\n		-- Phathotep, 24th Century B.C.",
"Be free and open and breezy!  Enjoy!",
"Beauty and harmony are as necessary to you as the very breath of life.",
"Change your thoughts and you change your world.",
"Communicate!  It can't make things any worse.",
"Courage is your greatest present need.",
"Do not sleep in a eucalyptus tree tonight.",
"Do nothing unless you must, and when you must act -- hesitate.",
"Do something unusual today.  Pay a bill.",
"Do what comes naturally.",
"Domestic happiness and faithful friends.",
"Don't go surfing in South Dakota for a while.",
"Don't kiss an elephant on the lips today.",
"Don't worry so loud, your roommate can't think.",
"Don't Worry, Be Happy.\n		-- Meher Baba",
"Don't worry.  Life's too long.\n		-- Vincent Sardi, Jr.",
"Excellent day for putting Slinkies on an escalator.",
"Excellent time to become a missing person.",
"Executive ability is prominent in your make-up.",
]